using HR_system.DTOs.Settings;
using HR_system.Middleware;
using HR_system.Services.Interfaces;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace HR_system.Services
{
    public class WhatsAppSettingsService : IWhatsAppSettingsService
    {
        private readonly IWhatsAppService _whatsAppService;
        private readonly ILogger<WhatsAppSettingsService> _logger;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public WhatsAppSettingsService(
            IWhatsAppService whatsAppService,
            ILogger<WhatsAppSettingsService> logger,
            IHttpContextAccessor httpContextAccessor)
        {
            _whatsAppService = whatsAppService;
            _logger = logger;
            _httpContextAccessor = httpContextAccessor;
        }

        public async Task<WhatsAppActionResultDto> SendTestPdfAsync(TestWhatsAppPdfDto dto)
        {
            using var scope = _logger.BeginScope(new Dictionary<string, object>
            {
                ["CorrelationId"] = GetCorrelationId(),
                ["PhoneNumber"] = dto.PhoneNumber
            });

            _logger.LogInformation("Starting WhatsApp test PDF send");

            if (string.IsNullOrWhiteSpace(dto.PhoneNumber))
            {
                return new WhatsAppActionResultDto
                {
                    Success = false,
                    Message = "رقم واتساب مطلوب"
                };
            }

            var pdfBytes = BuildTestPdf();
            var fileName = $"whatsapp-test-{DateTime.Now:yyyyMMdd-HHmmss}.pdf";

            var sendResult = await _whatsAppService.SendFileAsync(
                dto.PhoneNumber,
                fileName,
                "application/pdf",
                pdfBytes,
                string.IsNullOrWhiteSpace(dto.Caption) ? "اختبار إرسال ملف PDF من نظام الموارد البشرية" : dto.Caption);

            return new WhatsAppActionResultDto
            {
                Success = sendResult.Success,
                Message = sendResult.Success
                    ? "تم إرسال ملف PDF التجريبي بنجاح"
                    : "فشل إرسال PDF التجريبي. تحقق من حالة الجلسة وسجل OpenWA."
            };
        }

        private string GetCorrelationId()
        {
            return _httpContextAccessor.HttpContext?.Items[CorrelationIdMiddleware.ItemKey]?.ToString()
                   ?? _httpContextAccessor.HttpContext?.TraceIdentifier
                   ?? Guid.NewGuid().ToString("N");
        }

        private static byte[] BuildTestPdf()
        {
            return Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(24);
                    page.DefaultTextStyle(x => x.FontSize(12));

                    page.Content().Column(column =>
                    {
                        column.Spacing(8);
                        column.Item().Text("HR System WhatsApp Test PDF").SemiBold().FontSize(20).AlignCenter();
                        column.Item().Text($"Created At: {DateTime.Now:yyyy-MM-dd HH:mm:ss}").AlignCenter();
                        column.Item().PaddingTop(8).Text("This is a test file generated by HR System to validate WhatsApp PDF delivery.");
                        column.Item().PaddingTop(4).Text("هذا ملف تجريبي للتأكد من نجاح إرسال PDF عبر واتساب.");
                        column.Item().PaddingTop(10).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                    });
                });
            }).GeneratePdf();
        }
    }
}