// <auto-generated />
using System;
using HR_system.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HR_system.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251222163241_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HR_system.Models.Advance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Employee_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Employee_id");

                    b.ToTable("Advances");
                });

            modelBuilder.Entity("HR_system.Models.Attendence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan?>("Check_In_time")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("Check_out_time")
                        .HasColumnType("time");

                    b.Property<int>("Employee_id")
                        .HasColumnType("int");

                    b.Property<bool>("Is_Absent")
                        .HasColumnType("bit");

                    b.Property<int>("Permission_time")
                        .HasColumnType("int");

                    b.Property<DateTime>("Work_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Worked_minutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Employee_id");

                    b.ToTable("Attendences");
                });

            modelBuilder.Entity("HR_system.Models.Bounes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Employee_id")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Employee_id");

                    b.ToTable("Bounes");
                });

            modelBuilder.Entity("HR_system.Models.Deduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Employee_id")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Employee_id");

                    b.ToTable("Deductions");
                });

            modelBuilder.Entity("HR_system.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("HR_system.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Department_id")
                        .HasColumnType("int");

                    b.Property<string>("Emp_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Rate_latetime_multiplier")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Rate_overtime_multiplier")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Shift_id")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Department_id");

                    b.HasIndex("Shift_id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HR_system.Models.LateTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attendence_id")
                        .HasColumnType("int");

                    b.Property<int>("Minutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Attendence_id")
                        .IsUnique();

                    b.ToTable("LateTimes");
                });

            modelBuilder.Entity("HR_system.Models.OverTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attendence_id")
                        .HasColumnType("int");

                    b.Property<int>("Minutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Attendence_id")
                        .IsUnique();

                    b.ToTable("OverTimes");
                });

            modelBuilder.Entity("HR_system.Models.PayRoll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Base_salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Date_saved")
                        .HasColumnType("datetime2");

                    b.Property<int>("Employee_id")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<decimal>("Netsalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Number_of_absents_day")
                        .HasColumnType("int");

                    b.Property<int>("Number_of_holidays")
                        .HasColumnType("int");

                    b.Property<int>("Number_of_worked_days")
                        .HasColumnType("int");

                    b.Property<bool>("Payed")
                        .HasColumnType("bit");

                    b.Property<decimal>("Rate_lateTime")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rate_overtime")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Salary_actual_paid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Salary_per_hour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Total_added_hour")
                        .HasColumnType("int");

                    b.Property<decimal>("Total_advance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total_bounes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total_deduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Total_hours_in_this_month")
                        .HasColumnType("int");

                    b.Property<int>("Total_hours_in_work_time")
                        .HasColumnType("int");

                    b.Property<int>("Total_lateTime")
                        .HasColumnType("int");

                    b.Property<int>("Total_overtime")
                        .HasColumnType("int");

                    b.Property<int>("Total_worked_hours")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Employee_id");

                    b.ToTable("PayRolls");
                });

            modelBuilder.Entity("HR_system.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("End_time")
                        .HasColumnType("time");

                    b.Property<int>("Minutes_allow_attendence")
                        .HasColumnType("int");

                    b.Property<int>("Minutes_allow_departure")
                        .HasColumnType("int");

                    b.Property<string>("Shift_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("StandardHours")
                        .HasColumnType("decimal(4,2)");

                    b.Property<TimeSpan>("Start_time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("HR_system.Models.Advance", b =>
                {
                    b.HasOne("HR_system.Models.Employee", "Employee")
                        .WithMany("Advances")
                        .HasForeignKey("Employee_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HR_system.Models.Attendence", b =>
                {
                    b.HasOne("HR_system.Models.Employee", "Employee")
                        .WithMany("Attendences")
                        .HasForeignKey("Employee_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HR_system.Models.Bounes", b =>
                {
                    b.HasOne("HR_system.Models.Employee", "Employee")
                        .WithMany("Bounes")
                        .HasForeignKey("Employee_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HR_system.Models.Deduction", b =>
                {
                    b.HasOne("HR_system.Models.Employee", "Employee")
                        .WithMany("Deductions")
                        .HasForeignKey("Employee_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HR_system.Models.Employee", b =>
                {
                    b.HasOne("HR_system.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("Department_id");

                    b.HasOne("HR_system.Models.Shift", "Shift")
                        .WithMany("Employees")
                        .HasForeignKey("Shift_id");

                    b.Navigation("Department");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("HR_system.Models.LateTime", b =>
                {
                    b.HasOne("HR_system.Models.Attendence", "Attendence")
                        .WithOne("LateTime")
                        .HasForeignKey("HR_system.Models.LateTime", "Attendence_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendence");
                });

            modelBuilder.Entity("HR_system.Models.OverTime", b =>
                {
                    b.HasOne("HR_system.Models.Attendence", "Attendence")
                        .WithOne("OverTime")
                        .HasForeignKey("HR_system.Models.OverTime", "Attendence_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendence");
                });

            modelBuilder.Entity("HR_system.Models.PayRoll", b =>
                {
                    b.HasOne("HR_system.Models.Employee", "Employee")
                        .WithMany("PayRolls")
                        .HasForeignKey("Employee_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HR_system.Models.Attendence", b =>
                {
                    b.Navigation("LateTime");

                    b.Navigation("OverTime");
                });

            modelBuilder.Entity("HR_system.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HR_system.Models.Employee", b =>
                {
                    b.Navigation("Advances");

                    b.Navigation("Attendences");

                    b.Navigation("Bounes");

                    b.Navigation("Deductions");

                    b.Navigation("PayRolls");
                });

            modelBuilder.Entity("HR_system.Models.Shift", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
